/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        surface: "#f8f9fb",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dae2ff",
        "surface-container-high": "#e7e8ea",
        "inverse-primary": "#b2c5ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005235",
        outline: "#737685",
        "on-primary-container": "#c4d2ff",
        "on-secondary-container": "#475a7e",
        "surface-container-low": "#f3f4f6",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#041b3c",
        "secondary-fixed-dim": "#b4c7f1",
        "on-tertiary-fixed": "#002113",
        "primary-fixed-dim": "#b2c5ff",
        background: "#f8f9fb",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1e",
        "on-surface-variant": "#434654",
        "inverse-on-surface": "#f0f1f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e2e4",
        primary: "#003d9b",
        "secondary-container": "#bfd2fd",
        "outline-variant": "#c3c6d6",
        "primary-container": "#0052cc",
        secondary: "#4c5e83",
        "on-surface": "#191c1e",
        "surface-tint": "#0c56d0",
        "surface-container": "#edeef0",
        "on-primary-fixed": "#001848",
        "on-error": "#ffffff",
        "surface-variant": "#e1e2e4",
        "surface-dim": "#d9dadc",
        "tertiary-container": "#006844",
        "on-secondary-fixed-variant": "#34476a",
        "on-primary-fixed-variant": "#0040a2",
        "tertiary-fixed-dim": "#65dca4",
        "secondary-fixed": "#d7e2ff",
        "surface-bright": "#f8f9fb",
        "on-tertiary-container": "#72e9af",
        tertiary: "#004e32",
        "tertiary-fixed": "#82f9be",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "grid-gutter": "16px",
        sm: "8px",
        base: "4px",
        "table-cell-padding": "12px 16px",
        xl: "32px",
        xs: "4px",
        "sidebar-width": "240px",
        md: "16px",
        lg: "24px",
      },
      fontFamily: {
        "data-mono": ['"JetBrains Mono"', "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
