// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_A4VW6FECnFDuEwqnPmbnenEv-V16b9g',
    appId: '1:61569697681:web:443d5bcb6c86ac12dcbc30',
    messagingSenderId: '61569697681',
    projectId: 'canteen-app-e1c8d',
    authDomain: 'canteen-app-e1c8d.firebaseapp.com',
    storageBucket: 'canteen-app-e1c8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrbJ1ofNLVjPYyw4hCoRg__jm3PVqTdg',
    appId: '1:61569697681:android:7d42ab7e10374513dcbc30',
    messagingSenderId: '61569697681',
    projectId: 'canteen-app-e1c8d',
    storageBucket: 'canteen-app-e1c8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCA2FZp-KsyLQjvBPtlHaRQ6BjBW5xDG4',
    appId: '1:61569697681:ios:97992dcc368bda16dcbc30',
    messagingSenderId: '61569697681',
    projectId: 'canteen-app-e1c8d',
    storageBucket: 'canteen-app-e1c8d.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCA2FZp-KsyLQjvBPtlHaRQ6BjBW5xDG4',
    appId: '1:61569697681:ios:97992dcc368bda16dcbc30',
    messagingSenderId: '61569697681',
    projectId: 'canteen-app-e1c8d',
    storageBucket: 'canteen-app-e1c8d.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_A4VW6FECnFDuEwqnPmbnenEv-V16b9g',
    appId: '1:61569697681:web:25d042fbced62c07dcbc30',
    messagingSenderId: '61569697681',
    projectId: 'canteen-app-e1c8d',
    authDomain: 'canteen-app-e1c8d.firebaseapp.com',
    storageBucket: 'canteen-app-e1c8d.firebasestorage.app',
  );
}
